'use strict';
const {randomUUID,createHmac}=require('node:crypto');
const {parse}=require('csv-parse/sync');
class Fault extends Error { constructor(status,message){super(message);this.status=status;} }
function ensure(ok,message,status=400){if(!ok)throw new Fault(status,message);}
function text(v,max=5000){ensure(typeof v==='string'&&v.trim().length>0&&v.length<=max,'Missing or invalid text.');return v.trim();}
function number(v){ensure(Number.isSafeInteger(v)&&v>=0&&v<=1000000,'Credits must be whole numbers from 0 to 1,000,000.');return v;}
function id(v){ensure(typeof v==='string'&&/^[A-Z0-9_-]{1,40}$/.test(v),'Invalid ID. Use uppercase letters, numbers, - or _.');return v;}
function initial(){return {_id:'event',revision:0,publicRevision:0,phase:'preparation',reviewEndsAt:null,teams:[],problems:[],controller:null,auction:{sequence:0,problemId:null,price:0,leader:null,status:'upcoming'},updatedAt:new Date().toISOString()};}
function code(team,secret){return createHmac('sha256',secret).update('team-code:'+team.id+':'+team.codeVersion).digest('base64url').slice(0,14);}
function csvRows(input){let rows;try{rows=parse(text(input,150000),{columns:h=>h.map(x=>x.trim().toLowerCase().replace(/[ _]/g,'')),skip_empty_lines:true,bom:true,trim:true});}catch{throw new Fault(400,'Invalid CSV. Use the provided template.');}ensure(rows.length>0&&rows.length<=200,'Import 1–200 teams at a time.');const seen=new Set();return rows.map(r=>{const teamId=id(String(r.teamid||'').toUpperCase());ensure(!seen.has(teamId),'Duplicate team ID in CSV: '+teamId);seen.add(teamId);ensure(/^\d+$/.test(r.finalcredits||''),'Final Credits must be a nonnegative integer.');return {id:teamId,name:text(r.teamname,100),leader:text(r.teamleader,100),starting:number(Number(r.finalcredits)),spent:0,assignment:null,revealed:false,codeVersion:randomUUID()};});}
function publicProblem(p){return {id:p.id,title:p.title,theme:p.theme,brief:p.brief,startingPrice:p.startingPrice};}
function publicState(s){return {revision:s.publicRevision,phase:s.phase,reviewEndsAt:s.reviewEndsAt,problems:s.problems.filter(p=>p.published).map(p=>({...publicProblem(p),allocated:s.teams.some(t=>t.assignment===p.id)}))};}
function teamState(s,teamId){const t=s.teams.find(t=>t.id===teamId);ensure(t,'Team access was revoked.',401);const p=s.problems.find(p=>p.id===t.assignment);return {...publicState(s),team:{id:t.id,name:t.name,starting:t.starting,spent:t.spent,available:t.starting-t.spent},assignment:p?{...publicProblem(p),constraints:t.revealed?p.constraints:null,revealed:t.revealed}:null};}
function lease(s,owner){ensure(s.controller&&s.controller.owner===owner&&s.controller.expires>Date.now(),'Acquire auction control first.',409);}
function apply(s,action,b,actor){let result={ok:true};const now=Date.now();switch(action){
case 'import':{const rows=csvRows(b.csv);const added=rows.filter(r=>!s.teams.some(t=>t.id===r.id));ensure(s.teams.length+added.length<=200,'Maximum 200 teams.');s.teams.push(...added);result={ok:true,added:added.length,skipped:rows.length-added.length};break;}
case 'problem':{const p={id:id(b.id),title:text(b.title,150),theme:text(b.theme,80),brief:text(b.brief,6000),constraints:text(b.constraints,6000),startingPrice:number(b.startingPrice),published:false};const i=s.problems.findIndex(x=>x.id===p.id);if(i>=0){ensure(!s.problems[i].published&&!s.teams.some(t=>t.assignment===p.id),'Published or allocated briefs are locked. Unpublish an unassigned brief before editing.');s.problems[i]=p;}else{ensure(s.problems.length<20,'Maximum 20 problem statements.');s.problems.push(p);}break;}
case 'publish':{ensure(Array.isArray(b.ids)&&b.ids.length>0,'Select problems.');for(const pid of b.ids){const p=s.problems.find(p=>p.id===pid);ensure(p,'Unknown problem.');ensure(b.published===true||!s.teams.some(t=>t.assignment===pid),'An assigned problem cannot be unpublished.');p.published=b.published===true;}break;}
case 'phase':{ensure(['preparation','review','bidding','work','closed'].includes(b.phase),'Invalid phase.');if(b.phase==='review'){ensure(s.problems.some(p=>p.published),'Publish problems first.');ensure(Number.isInteger(b.minutes)&&b.minutes>=1&&b.minutes<=60,'Review time must be 1–60 minutes.');s.reviewEndsAt=new Date(now+b.minutes*60000).toISOString();}else s.reviewEndsAt=null;s.phase=b.phase;break;}
case 'claim':{ensure(typeof b.owner==='string'&&b.owner.length>=16&&b.owner.length<=100,'Invalid controller ID.');ensure(!s.controller||s.controller.expires<now||s.controller.owner===b.owner||b.takeover===true,'Another controller is active. Use explicit takeover.',409);s.controller={owner:b.owner,expires:now+120000};result={ok:true,sequence:s.auction.sequence};break;}
case 'auction':{lease(s,b.owner);ensure(Number.isSafeInteger(b.sequence)&&b.sequence>s.auction.sequence,'Stale auction update.',409);const p=s.problems.find(p=>p.id===b.problemId);ensure(p&&p.published,'Select a released problem.');ensure(['upcoming','open','unsold'].includes(b.status),'Invalid display status.');ensure(!b.leader||s.teams.some(t=>t.id===b.leader),'Unknown leading team.');s.auction={sequence:b.sequence,problemId:p.id,price:number(b.price),leader:b.leader||null,status:b.status};s.controller.expires=now+120000;break;}
case 'sale':{lease(s,b.owner);ensure(s.phase==='bidding','Open the bidding phase first.');const t=s.teams.find(t=>t.id===b.teamId);const p=s.problems.find(p=>p.id===b.problemId);ensure(t&&p&&p.published,'Select a team and released problem.');const price=number(b.price);ensure(price>=p.startingPrice,'Bid is below the starting price.');ensure(!t.assignment,'Team already has a problem.',409);ensure(!s.teams.some(x=>x.assignment===p.id),'Problem already allocated.',409);ensure(t.starting-t.spent>=price,'Insufficient credits.',409);t.spent+=price;t.assignment=p.id;t.revealed=false;s.auction={sequence:s.auction.sequence+1,problemId:p.id,price,leader:t.id,status:'sold'};result={ok:true,teamId:t.id,problemId:p.id,price,available:t.starting-t.spent};break;}
case 'reverse':{text(b.reason,300);const t=s.teams.find(t=>t.id===b.teamId);ensure(t&&t.assignment,'Team has no assignment.');ensure(!t.revealed,'Constraints have been seen. Reassignment is blocked; resolve with the event lead.');t.assignment=null;t.spent=0;t.revealed=false;s.auction={sequence:s.auction.sequence+1,problemId:null,price:0,leader:null,status:'upcoming'};break;}
case 'adjust':{text(b.reason,300);const t=s.teams.find(t=>t.id===b.teamId);ensure(t,'Unknown team.');const n=number(b.starting);ensure(n>=t.spent,'Starting credits cannot be below spent credits.');t.starting=n;break;}
case 'reveal':{ensure(Array.isArray(b.ids)&&b.ids.length>0,'Select assigned teams.');for(const tid of b.ids){const t=s.teams.find(t=>t.id===tid);ensure(t&&t.assignment,'Every selected team must have an assignment.');t.revealed=true;}break;}
case 'rotate':{const t=s.teams.find(t=>t.id===b.teamId);ensure(t,'Unknown team.');t.codeVersion=randomUUID();break;}
default:throw new Fault(404,'Unknown action.');}s.revision++;if(!['auction','claim'].includes(action))s.publicRevision++;s.updatedAt=new Date().toISOString();return result;}
module.exports={Fault,ensure,text,number,id,initial,code,csvRows,publicState,teamState,publicProblem,apply};
