const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const source=fs.readFileSync('public/auction.js','utf8');
function harness(cached,remote){const nodes=new Map();let receiver;const timers=[];const listeners={};const local=new Map(cached?[['r2-public-display-v1',JSON.stringify(cached)]]:[]);const document={body:{dataset:{page:'auction'}},documentElement:{},getElementById(id){if(!nodes.has(id))nodes.set(id,{});return nodes.get(id);}};const context={document,window:{addEventListener:(n,f)=>listeners[n]=f},sessionStorage:{getItem:()=>null,setItem(){}},localStorage:{getItem:k=>local.get(k),setItem:(k,v)=>local.set(k,v)},crypto:{randomUUID:()=> 'test-display-owner-123456'},BroadcastChannel:class{constructor(){receiver=this;}},Date,JSON,Number,Math,AbortSignal,fetch:async()=>{if(remote instanceof Error)throw remote;return {ok:true,json:async()=>remote};},setTimeout:f=>{timers.push(f);},setInterval(){},clearTimeout(){}};vm.runInNewContext(source,context);return {nodes,channel:()=>receiver,listeners,local,timers};}
const state=(seq,price)=>({sequence:seq,problemId:'P1',price,status:'open',problems:[{id:'P1',title:'Campus reuse',theme:'Environment',brief:'Public brief',startingPrice:10}],leaderName:'Team A',synced:false});
test('projector restores public cached screen immediately without a network response',()=>{const h=harness(state(50,35),new Error('offline'));assert.equal(h.nodes.get('display-title').textContent,'Campus reuse');assert.equal(h.nodes.get('display-price').textContent,35);});
test('same-laptop price updates render synchronously',()=>{const h=harness(state(50,35),new Error('offline'));h.channel().onmessage({data:state(51,40)});assert.equal(h.nodes.get('display-price').textContent,40);});
test('out-of-order channel updates cannot roll back price',()=>{const h=harness(state(50,35),new Error('offline'));h.channel().onmessage({data:state(55,75)});h.channel().onmessage({data:state(52,45)});assert.equal(h.nodes.get('display-price').textContent,75);});
test('server response cannot overwrite a newer unsaved local display',async()=>{const h=harness(state(50,35),{...state(40,20),synced:true});await new Promise(r=>setImmediate(r));assert.equal(h.nodes.get('display-price').textContent,35);});
test('connection failure preserves visible problem and bid',async()=>{const h=harness(state(50,35),new Error('offline'));await new Promise(r=>setImmediate(r));assert.equal(h.nodes.get('display-price').textContent,35);assert.match(h.nodes.get('display-sync').textContent,/Connection interrupted/);});
test('HTML-like problem text is displayed as text rather than injected HTML',()=>{const s=state(1,10);s.problems[0].title='<img src=x onerror=alert(1)>';const h=harness(s,new Error('offline'));assert.equal(h.nodes.get('display-title').textContent,s.problems[0].title);assert.equal(h.nodes.get('display-title').innerHTML,undefined);});
