'use strict';
const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');const {MongoMemoryReplSet}=require('mongodb-memory-server');const {createStore}=require('../lib/store');const {createApp}=require('../server');const {code}=require('../lib/domain');
let mongo,store,server,base,adminCookie;const secret='test-only-secret-not-for-production-1234567890',password='test-only-admin-password';const owner='controller-owner-test-123456';
async function request(route,{body,cookie,key,headers={}}={}){const r=await fetch(base+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Round-Two':'1',...(cookie?{Cookie:cookie}:{}),...(key?{'Idempotency-Key':key}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});const ct=r.headers.get('content-type');return {status:r.status,headers:r.headers,data:ct?.includes('application/json')?await r.json():await r.text()};}
async function action(name,body,key=randomUUID()){return request('/api/admin/'+name,{body,cookie:adminCookie,key});}
const problem=(id)=>({id,title:'Challenge '+id,theme:'Campus',brief:'A public brief '+id,constraints:'PRIVATE TWIST '+id,startingPrice:10});
before(async()=>{if(process.env.ROUND2_TEST_MEMORY==='1'){store=require('./memory-store').memoryStore();console.log('HTTP tests use a memory test double; MongoDB transaction verification is a separate suite.');}else{mongo=await MongoMemoryReplSet.create({replSet:{count:1},binary:{version:'7.0.24'}});store=createStore(mongo.getUri(),'mindtech_round2_test_integration');}const app=createApp({store,secret,password,secure:false});server=app.listen(0);await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;await store.db();const r=await request('/api/login',{body:{role:'admin',password}});assert.equal(r.status,200);adminCookie=r.headers.get('set-cookie').split(';')[0];});
after(async()=>{if(server)await new Promise(r=>server.close(r));if(store)await store.close();if(mongo)await mongo.stop();});
test('database guard refuses the Round 1 database',()=>{assert.throws(()=>createStore('mongodb://localhost','mindtech_arena'),/isolated/);});
test('public pages, no stale validators, CSP and no credential files',async()=>{for(const path of ['/','/admin','/board']){const r=await request(path,{headers:{'If-None-Match':'anything','If-Modified-Since':'Wed, 01 Jan 2030 00:00:00 GMT'}});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.ok(r.headers.get('content-security-policy').includes("frame-ancestors 'none'"));}for(const path of ['/auction','/auction.html','/round-two/auction'])assert.equal((await request(path)).status,401);for(const path of ['/.env','/server.js','/lib/domain.js'])assert.equal((await request(path)).status,404);});
test('admin APIs require login; incorrect password and cross-origin writes rejected',async()=>{for(const path of ['/api/public','/api/board','/api/display'])assert.equal((await request(path)).status,401);assert.equal((await request('/api/admin/state')).status,401);assert.equal((await request('/api/login',{body:{role:'admin',password:'wrong'}})).status,401);assert.equal((await request('/api/login',{body:{role:'admin',password},headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await request('/api/login',{body:{role:'admin',password},headers:{'X-Round-Two':'0'}})).status,403);});
test('CSV import preview, validation, duplicate import preservation',async()=>{const csv='Team ID,Team Name,Team Leader,Final Credits\nT1,"Team, One",Leader One,100\nT2,Team Two,Leader Two,100\nT3,Team Three,Leader Three,100';const p=await request('/api/admin/import-preview',{body:{csv},cookie:adminCookie});assert.equal(p.status,200);assert.equal(p.data[0].name,'Team, One');assert.equal((await action('import',{csv})).data.added,3);assert.equal((await action('import',{csv})).data.skipped,3);for(const bad of ['Team ID,Team Name,Team Leader,Final Credits\nT1,One,Lead,-1','Team ID,Team Name,Team Leader,Final Credits\nX,One,Lead,3\nX,Two,Lead,4'])assert.equal((await action('import',{csv:bad})).status,400);});
test('drafts stay hidden; publishing exposes briefs but never private constraints',async()=>{for(const id of ['PS01','PS02','PS03'])assert.equal((await action('problem',problem(id))).status,200);assert.equal((await request('/api/public',{cookie:adminCookie})).data.problems.length,0);await action('publish',{ids:['PS01','PS02','PS03'],published:true});const pub=await request('/api/public',{cookie:adminCookie});assert.equal(pub.data.problems.length,3);assert.ok(!JSON.stringify(pub.data).includes('PRIVATE'));assert.equal((await action('problem',problem('PS01'))).status,400);});
test('team login has secure cookie flags and cannot access admin routes',async()=>{const t=(await store.read()).teams[0];const r=await request('/api/login',{body:{teamId:t.id,code:code(t,secret)}});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);assert.match(r.headers.get('set-cookie'),/SameSite=Strict/);const cookie=r.headers.get('set-cookie').split(';')[0];assert.equal((await request('/api/admin/state',{cookie})).status,403);assert.equal((await request('/api/admin/codes',{cookie})).status,403);assert.ok(!JSON.stringify((await request('/api/me',{cookie})).data).includes('PRIVATE'));const named=await request('/api/login',{body:{teamId:'  team, one  ',code:' '+code(t,secret)+' '}});assert.equal(named.status,200);assert.equal((await request('/api/public',{cookie})).data.problems.length,3);});
test('controller ownership and stale update protection',async()=>{assert.equal((await action('claim',{owner})).status,200);assert.equal((await action('claim',{owner:'another-controller-123456'})).status,409);assert.equal((await action('auction',{owner,sequence:10,problemId:'PS01',price:20,status:'open'})).status,200);assert.equal((await action('auction',{owner,sequence:9,problemId:'PS01',price:15,status:'open'})).status,409);const pub=await request('/api/display',{cookie:adminCookie});assert.ok(!JSON.stringify(pub.data).includes('PRIVATE'));assert.equal(pub.data.price,20);});
test('review deadline is server persisted; bidding phase required for sales',async()=>{assert.equal((await action('sale',{owner,teamId:'T1',problemId:'PS01',price:20})).status,400);await action('phase',{phase:'review',minutes:15});const a=(await request('/api/public',{cookie:adminCookie})).data.reviewEndsAt;assert.equal(a,(await request('/api/public',{cookie:adminCookie})).data.reviewEndsAt);assert.ok(new Date(a)>new Date());await action('phase',{phase:'bidding'});});
test('sale updates allocation and credits once even after lost response retry',async()=>{const key=randomUUID(),body={owner,teamId:'T1',problemId:'PS01',price:35};const first=await action('sale',body,key);assert.equal(first.status,200);const repeat=await action('sale',body,key);assert.deepEqual(repeat.data,first.data);const t=(await store.read()).teams.find(t=>t.id==='T1');assert.equal(t.spent,35);assert.equal(t.starting,100);assert.equal(t.assignment,'PS01');assert.equal((await action('sale',{...body,price:36},key)).status,409);});
test('over-budget and duplicate allocation failures roll back all state',async()=>{assert.equal((await action('sale',{owner,teamId:'T2',problemId:'PS02',price:101})).status,409);assert.equal((await action('sale',{owner,teamId:'T2',problemId:'PS01',price:20})).status,409);const t=(await store.read()).teams.find(t=>t.id==='T2');assert.equal(t.spent,0);assert.equal(t.assignment,null);});
test('concurrent allocations have exactly one winner and no double spending',async()=>{const results=await Promise.all(['T2','T3'].map(teamId=>action('sale',{owner,teamId,problemId:'PS02',price:25})));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const s=await store.read();assert.equal(s.teams.filter(t=>t.assignment==='PS02').length,1);assert.equal(s.teams.reduce((sum,t)=>sum+t.spent,0),60);});
test('constraint reveal is team-specific and forbidden on public/projector endpoints',async()=>{await action('reveal',{ids:['T1']});const s=await store.read();for(const t of s.teams){const login=await request('/api/login',{body:{teamId:t.id,code:code(t,secret)}});const cookie=login.headers.get('set-cookie').split(';')[0];const me=await request('/api/me?teamId=T1',{cookie});if(t.id==='T1')assert.equal(me.data.assignment.constraints,'PRIVATE TWIST PS01');else assert.ok(!JSON.stringify(me.data).includes('PRIVATE TWIST'));}for(const path of ['/api/public','/api/display','/api/board'])assert.ok(!JSON.stringify((await request(path,{cookie:adminCookie})).data).includes('PRIVATE TWIST'));assert.equal((await action('reverse',{teamId:'T1',reason:'mistake'})).status,400);});
test('staged constraints stay hidden through authenticated HTTP until each release',async()=>{
 const body={...problem('PS04'),constraints:[1,2,3,4].map(i=>'Constraint '+i+': STAGE_SECRET_'+i).join('\n\n')};
 await action('problem',body);await action('publish',{ids:['PS04'],published:true});
 const t=(await store.read()).teams.find(t=>!t.assignment);assert.ok(t);await action('sale',{owner,teamId:t.id,problemId:'PS04',price:10});
 const login=await request('/api/login',{body:{teamId:t.id,code:code(t,secret)}});const cookie=login.headers.get('set-cookie').split(';')[0];
 for(let i=1;i<=4;i++){
  assert.equal((await action('reveal',{ids:[t.id]})).status,200);const me=(await request('/api/me',{cookie})).data;
  assert.equal(me.assignment.revealedCount,i);assert.ok(me.assignment.constraints.includes('STAGE_SECRET_'+i));
  for(let hidden=i+1;hidden<=4;hidden++)assert.ok(!JSON.stringify(me).includes('STAGE_SECRET_'+hidden));
  for(const route of ['/api/public','/api/display','/api/board'])assert.ok(!JSON.stringify((await request(route,{cookie:adminCookie})).data).includes('STAGE_SECRET'));
 }
 assert.equal((await action('reveal',{ids:[t.id]})).status,400);
});
test('unrevealed sale reversal refunds credits and releases problem',async()=>{const s=await store.read(),t=s.teams.find(t=>t.assignment==='PS02');await action('reverse',{teamId:t.id,reason:'Organiser correction'});const updated=(await store.read()).teams.find(x=>x.id===t.id);assert.equal(updated.spent,0);assert.equal(updated.assignment,null);const log=await store.audit();assert.ok(log.some(x=>x.action==='reverse'&&x.detail.reason==='Organiser correction'));});
test('code rotation revokes old sessions and old access code',async()=>{const t=(await store.read()).teams[0];const old=code(t,secret);const login=await request('/api/login',{body:{teamId:t.id,code:old}});const cookie=login.headers.get('set-cookie').split(';')[0];await action('rotate',{teamId:t.id});assert.equal((await request('/api/me',{cookie})).status,401);assert.equal((await request('/api/login',{body:{teamId:t.id,code:old}})).status,401);});
test('public revision does not churn with price updates; unchanged team polling is tiny',async()=>{const t=(await store.read()).teams[1];const login=await request('/api/login',{body:{teamId:t.id,code:code(t,secret)}});const cookie=login.headers.get('set-cookie').split(';')[0];const me=(await request('/api/me',{cookie})).data;await action('auction',{owner,sequence:100,problemId:'PS03',price:20,status:'open'});const r=await request('/api/me?version='+me.revision,{cookie});assert.equal(r.data.unchanged,true);assert.ok(JSON.stringify(r.data).length<100);});
test('tampered session rejected and logout clears cookie',async()=>{assert.equal((await request('/api/me',{cookie:adminCookie+'x'})).status,401);const r=await request('/api/logout',{body:{},cookie:adminCookie});assert.match(r.headers.get('set-cookie'),/Max-Age=0/);});
test('concurrent read load: 100 requests preserve isolation',async()=>{const start=performance.now();const responses=await Promise.all(Array.from({length:100},()=>request('/api/public',{cookie:adminCookie})));assert.ok(responses.every(r=>r.status===200&&!JSON.stringify(r.data).includes('PRIVATE')));console.log('100 concurrent local reads: '+Math.round(performance.now()-start)+'ms total (not a production latency guarantee)');});
test('database outage fails closed and does not report a sale success',async()=>{await store.close();const r=await action('sale',{owner,teamId:'T3',problemId:'PS03',price:20});assert.equal(r.status,503);assert.ok(!r.data.ok);});
